# Generated by Django 5.2 on 2025-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pecas/')),
            ],
        ),
    ]
